import Head from "next/head";
import React, { useState } from "react";
import Image from "next/image";
import { Icon } from "../icons/Icon";
import Link from "next/link";
import Slider from "../components/slider";
import { useRouter } from 'next/router'

export default function AlterationDetail() {
  const router = useRouter()
  let [isOpen, setIsOpen] = useState(false)

  const toggleSlider = () => {
    setIsOpen(!isOpen);
  };

  return (
    <>

      <Head>
        <title>Ev Tadilat Detay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span className="w-full bg-[#F9B399] h-[6px]"></span>
      <div className="w-full flex justify-between">
        <div className="flex">
          <div>
            <Image src="/detail1.png" width={242} height={300} />
          </div>
          <span className="pt-48">
            <Icon name="leftCloud" />
          </span>
          <div>
            <Image src="/detail2.png" width={350} height={242} />
          </div>
        </div>

        <div className="flex pr-12 pt-11">
          <span className="mr-32">
            <Icon name="rightCloud" />
          </span>
          <Link href="/">
            <span className="w-[50px]  h-[50px] rounded-full flex cursor-pointer justify-center items-center text-[#57544F] text-xl bg-[#57544f33]">
              X
            </span>
          </Link>
        </div>
      </div>

      <div className="container mx-auto">
        <div className="flex justify-center ">
          <div className="flex flex-col pr-20">
            <h1 className="font-amatic font-bold text-7xl text-black">
              GÜLER TAŞDEMİR
            </h1>
            <p className="text-[#57544F] font-jakarta font-semibold text-xs pt-5">
              TADİLAT DURUMU
            </p>
            <p className="text-black font-jakarta font-normal text-xl">
              Balkon Tadilatı
            </p>
            <p className="text-[#57544F] font-jakarta font-semibold text-xs pt-5">
              Maliyet
            </p>
            <p className="text-black font-jakarta font-normal text-xl">
              3.000Tl
            </p>
            <div className="pt-8">
              <button onClick={()=>router.push('/support')} className="w-28 h-10 bg-[#E6EEE3] rounded-[5px] text-[#3C4439] text-sm font-jakarta font-medium">
                Destek Ver
              </button>
            </div>
          </div>
          <div className="w-[35rem]">
            <p>
              Görüşme müracaatçının 13 yaşındaki kızı Yağmur Hanım ile
              gerçekleştirilmiştir. Yağmur Hanım evde annesi ve 1,5 yaşındaki
              kız kardeşi ile birlikte gecekondu tipi bir evde 500TL kira bedeli
              ödeyerek yaşadıklarını beyan etmiştir. Yağmur Hanım annesi ve
              babasının yeni boşandığını, babasının herhangi bir nafaka
              ödemesinde bulunmadığını, geçimlerini annesinin günlük gittiği
              tarla işleri ve çevre yardımlarını ile sağladıklarını ifade
              etmiştir. Evin genel durumu bir oda, bir mutfak, banyo ve
              tuvaletten oluşmaktadır. Banyo ve tuvalet duvarlarında rutubet
              oluşumu olduğu gözlemlenmiştir.
            </p>
          </div>
        </div>
        <div>
        <Slider isOpen={isOpen} setIsOpen={setIsOpen} />
        </div>

        <div className="flex justify-center  pt-28">
 
          <div >
            <Image onClick={toggleSlider} src="/destekDetay1.png" width={350} height={300} />
          </div>
          <div className="mx-6">
            <Image onClick={toggleSlider} src="/destekDetay1.png" width={350} height={300} />
          </div>
          <div>
            <Image onClick={toggleSlider} src="/destekDetay1.png" width={350} height={300} />
          </div>
        </div>
        <div className="flex flex-col">
          <div className="flex justify-center pt-40">
            <h1 className="cursor-pointer font-amatic font-bold text-[40px] text-headerColor">
              DİĞER TADİLAT BEKLEYEN EVLER
            </h1>
          </div>
          <div className="bg-white flex justify-evenly rounded-xl mb-5 mt-5">
            <div className="flex items-center py-5">
              <Image src="/gallery2.png" width={60} height={60} />
              <div className="flex flex-col">
                <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                  AD SOYAD
                </p>
                <p className="font-jakarta font-normal text-xl text-black">
                  Güler Taşdemir
                </p>
              </div>
              <div className="flex flex-col px-12">
                <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                  TELEFON
                </p>
                <p className="font-jakarta font-normal text-xl text-black">
                  05539335203
                </p>
              </div>
              <div className="flex flex-col">
                <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                  TADİLAT DURUMU
                </p>
                <p className="font-jakarta font-normal text-xl text-black">
                  Balkon Tadilatı
                </p>
              </div>
              <div className="flex flex-col px-12">
                <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                  MALİYET
                </p>
                <p className="font-jakarta font-normal text-xl text-black ">
                  3,000Tl
                </p>
              </div>
            </div>
            <div className="flex items-center">
              <button
                onClick={() => router.push("/alterationDetail")}
                className="bg-white border border-[#BBB8B3] rounded-md w-28 h-10 mr-5"
              >
                Detayı Gör
              </button>
              <button onClick={()=>router.push('/support')} className="bg-[#E6EEE3] border border-[#BBB8B3] rounded-md w-28 h-10 ">
                Destek Ver
              </button>
            </div>
          </div>
          <div className="bg-white flex justify-evenly rounded-xl mb-5">
            <div className="flex items-center py-5">
              <Image src="/gallery2.png" width={60} height={60} />
              <div className="flex flex-col">
                <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                  AD SOYAD
                </p>
                <p className="font-jakarta font-normal text-xl text-black">
                  Güler Taşdemir
                </p>
              </div>
              <div className="flex flex-col px-12">
                <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                  TELEFON
                </p>
                <p className="font-jakarta font-normal text-xl text-black">
                  05539335203
                </p>
              </div>
              <div className="flex flex-col">
                <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                  TADİLAT DURUMU
                </p>
                <p className="font-jakarta font-normal text-xl text-black">
                  Balkon Tadilatı
                </p>
              </div>
              <div className="flex flex-col px-12">
                <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                  MALİYET
                </p>
                <p className="font-jakarta font-normal text-xl text-black ">
                  3,000Tl
                </p>
              </div>
            </div>
            <div className="flex items-center">
              <button
                onClick={() => router.push("/alterationDetail")}
                className="bg-white border border-[#BBB8B3] rounded-md w-28 h-10 mr-5"
              >
                Detayı Gör
              </button>
              <button
             
              className="bg-[#E6EEE3] border border-[#BBB8B3] rounded-md w-28 h-10 ">
                Destek Ver
              </button>
            </div>
          </div>
        </div>
      </div>
      <Image src="/bg.png" layout="responsive" width={40} height={5} objectFit="cover"  />
    </>
  );
}
