import Head from "next/head";
import React, { useState } from "react";
import Image from "next/image";
import { Icon } from "../icons/Icon";
import Link from "next/link";
import Slider from "../components/slider";
import { useRouter } from "next/router";

export default function AlterationDetail() {
  const router = useRouter();
  let [isOpen, setIsOpen] = useState(false);

  const toggleSlider = () => {
    setIsOpen(!isOpen);
  };

  return (
    <>
      <Head>
        <title>Ev Tadilat Detay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span className="w-full bg-[#F9B399] h-[6px]"></span>
      <div className="w-full flex md:justify-between">
        <div className="flex">
          <div>
            <Image src="/detail1.png" width={242} height={300} />
          </div>
          <span className="md:pt-48">
            <Icon name="leftCloud" />
          </span>
          <div>
            <Image src="/detail2.png" width={350} height={242} />
          </div>
        </div>

        <div className="flex flex-col md:flex-row md:pr-12 pt-11">
          <span className="md:mr-32 hidden md:flex">
            <Icon name="rightCloud" />
          </span>
          <span className="flex justify-end">

            <Link href="/">
              <span className="md:w-[50px] w-10 h-10  md:h-[50px] rounded-full flex cursor-pointer justify-center items-center text-[#57544F] text-xl bg-[#57544f33]">
                X
              </span>
            </Link>
          </span>
        </div>
      </div>

      <div className="container mx-auto">
        <div className="flex justify-center md:flex-row flex-col">
          <div className="flex flex-col pr-20 md:items-start items-center ">
            <h1 className="font-amatic font-bold text-4xl md:text-7xl text-black">
              GÜLER TAŞDEMİR
            </h1>
            <p className="text-[#57544F] font-jakarta font-semibold text-xs pt-5">
              TADİLAT DURUMU
            </p>
            <p className="text-black font-jakarta font-normal text-xl">
              Balkon Tadilatı
            </p>
            <p className="text-[#57544F] font-jakarta font-semibold text-xs pt-5">
              Maliyet
            </p>
            <p className="text-black font-jakarta font-normal text-xl">
              3.000Tl
            </p>
            <div className="pt-8">
              <button
                onClick={() => router.push("/support")}
                className="w-28 h-10 bg-[#E6EEE3] rounded-[5px] text-[#3C4439] text-sm font-jakarta font-medium"
              >
                Destek Ver
              </button>
            </div>
          </div>
          <div className="md:w-[35rem] px-10 pt-10 md:px-0 md:pt-0">
            <p>
              Görüşme müracaatçının 13 yaşındaki kızı Yağmur Hanım ile
              gerçekleştirilmiştir. Yağmur Hanım evde annesi ve 1,5 yaşındaki
              kız kardeşi ile birlikte gecekondu tipi bir evde 500TL kira bedeli
              ödeyerek yaşadıklarını beyan etmiştir. Yağmur Hanım annesi ve
              babasının yeni boşandığını, babasının herhangi bir nafaka
              ödemesinde bulunmadığını, geçimlerini annesinin günlük gittiği
              tarla işleri ve çevre yardımlarını ile sağladıklarını ifade
              etmiştir. Evin genel durumu bir oda, bir mutfak, banyo ve
              tuvaletten oluşmaktadır. Banyo ve tuvalet duvarlarında rutubet
              oluşumu olduğu gözlemlenmiştir.
            </p>
          </div>
        </div>
        <div>
          <Slider isOpen={isOpen} setIsOpen={setIsOpen} />
        </div>

        <div className="flex items-center justify-center md:flex-row flex-col pt-28">
          <div>
            <Image
              onClick={toggleSlider}
              src="/destekDetay1.png"
              width={350}
              height={300}
            />
          </div>
          <div className="mx-6">
            <Image
              onClick={toggleSlider}
              src="/destekDetay1.png"
              width={350}
              height={300}
            />
          </div>
          <div>
            <Image
              onClick={toggleSlider}
              src="/destekDetay1.png"
              width={350}
              height={300}
            />
          </div>
        </div>
        <div className="flex flex-col">
          <div className="flex justify-center pt-40">
            <h1 className="cursor-pointer font-amatic font-bold text-[40px] text-headerColor">
              DİĞER TADİLAT BEKLEYEN EVLER
            </h1>
          </div>
          <section class="mb-48 mt-5">
            <div class="bg-white alert alert-dismissible rounded-lg py-4 px-6 text-black md:flex justify-between items-center text-center md:text-left">
              <div className="w-auto flex justify-center items-center flex-col md:flex-row">
                <div class="mb-4 md:mb-0 flex items-center flex-wrap justify-center md:justify-start relative md:mr-32">
                  <span className="w-14 md:absolute md:left-0 ">
                    <img src="/destekDetay1.png" />
                  </span>
                  <span className="w-14 md:absolute md:left-8">
                    <img src="/destekDetay1.png" />
                  </span>
                  <span className="w-14 md:absolute md:left-16 ">
                    <img src="/destekDetay1.png" />
                  </span>
                </div>
                <div class="mb-4 md:mb-0 flex items-center flex-wrap justify-center  md:justify-start md:mx-[50px]">
                  <div className="flex flex-col">
                    <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                      AD SOYAD
                    </p>
                    <p className="font-jakarta font-normal text-xl text-black">
                      Muslum Dogan
                    </p>
                  </div>
                </div>
                <div class="mb-4 md:mb-0 flex items-center flex-wrap justify-center md:justify-start">
                  <div className="flex flex-col">
                    <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                      TELEFON
                    </p>
                    <p className="font-jakarta font-normal text-xl text-black">
                      05539335203
                    </p>
                  </div>
                </div>
                <div class="mb-4 md:mb-0 flex items-center flex-wrap justify-center md:justify-start md:mx-[50px]">
                  <div className="flex flex-col">
                    <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                      TADİLAT DURUMU
                    </p>
                    <p className="font-jakarta font-normal text-xl text-black">
                      Balkon Tadilatı
                    </p>
                  </div>
                </div>
                <div class="mb-4 md:mb-0 flex items-center flex-wrap justify-center md:justify-start">
                  <div className="flex flex-col">
                    <p className="font-jakarta font-semibold text-xs text-[#57544F]">
                      MALİYET
                    </p>
                    <p className="font-jakarta font-normal text-xl text-black ">
                      8,000Tl
                    </p>
                  </div>
                </div>
              </div>
              <div class="flex items-center justify-center md:justify-end md:w-1/4">
                <button
                  onClick={() => router.push("/alterationDetail")}
                  class="inline-block px-5 py-[10px] bg-white border border-[#BBB8B3] text-black font-medium text-sm leading-tight uppercase rounded-[5px]  hover:bg-gray-100 hover:shadow-lg focus:bg-gray-100 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-gray-200 active:shadow-lg transition duration-150 ease-in-out mr-10"
                  href="#!"
                  role="button"
                  data-mdb-ripple="true"
                  data-mdb-ripple-color="light"
                >
                  Detayı Gör
                </button>
                <button
                  onClick={() => router.push("/support")}
                  class="inline-block px-5 py-[10px] bg-[#E6EEE3] text-black font-medium text-sm leading-tight uppercase rounded-[5px]  hover:bg-gray-100 hover:shadow-lg focus:bg-gray-100 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-gray-200 active:shadow-lg transition duration-150 ease-in-out "
                  href="#!"
                  role="button"
                  data-mdb-ripple="true"
                  data-mdb-ripple-color="light"
                >
                  Destek Ver
                </button>
              </div>
            </div>
          </section>
        </div>
      </div>
      <Image
        src="/bg.png"
        layout="responsive"
        width={40}
        height={5}
        objectFit="cover"
      />
    </>
  );
}
