import Head from "next/head";
import { Icon } from "../icons/Icon";
import Image from "next/image";
import imageStyle from "../styles/imageStyle.module.css";
import { useState } from "react";
import Alteration from "../components/alteration";
import Delivery from "../components/delivery";
export default function Home() {
  const [showHomes, setShowHomes] = useState(true);

  const changeHomes = () => {
    setShowHomes((showHomes = !showHomes));
  };

  return (
    <div className="bg-pageBg w-full h-screen ">
      <Head>
        <title>101 Ev Tadilat Projesi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEADER */}
      <div className="container mx-auto pb-48">
        <header className="w-full flex flex-col">
          <div className="flex flex-col pt-28 items-center">
            <h1 className="font-amatic  font-bold text-7xl text-black">
              101 EV
            </h1>
            <h1 className="font-amatic  font-bold text-7xl text-black relative">
              TADİLAT PROJESI
              <span className="absolute top-[-13px] right-0">
                <Icon name="heart" />
              </span>
            </h1>
          </div>
          <div className="flex justify-around items-center">
            <Icon name="leftCloud" />
            <Icon name="rightCloud" />
          </div>
          {/* <Icon name="iconHeader" size={100}/> */}
          <div>
            <Image src="/bg.png" width={1440} height={120} />
          </div>
          {/* <span className="after:content-[''] h-1 mt-[-1px] border border-[#57544F] bg-[#F9B399]"></span> */}
        </header>

        {/* CONTENT */}

        {/* TOTAL PRİCE */}
        <div className=" flex w-full flex-col md:flex-row justify-center items-center">
          <div className="lg:m-10 lg:p-12 p-8 m-5 rounded-lg bg-buttonBg  flex box-border">
            <div>
              <Icon name="book" />
            </div>
            <div className="flex flex-col items-center justify-center">
              <span className="font-jakarta font-semibold lg:text-4xl text-xl text-black">
                101
              </span>
              <span className="font-jakarta font-normal text-lg">
                Tadilat Bekleyen Ev
              </span>
            </div>
          </div>
          <div className="lg:p-12 lg:m-10 p-8 m-5 rounded-lg bg-buttonBg   flex box-border">
            <div>
              <Icon name="home" />
            </div>
            <div className="flex flex-col items-center justify-center">
              <span className="font-jakarta font-semibold lg:text-4xl text-xl text-black">
                71
              </span>
              <span className="font-jakarta font-normal text-lg">
                Teslim edilen Ev
              </span>
            </div>
          </div>
          <div className="lg:p-12 lg:m-10 p-8 m-5 rounded-lg bg-buttonBg   flex box-border">
            <div>
              <Icon name="money" />
            </div>
            <div className="flex flex-col items-center justify-center">
              <span className="font-jakarta font-semibold lg:text-4xl text-xl text-black">
                9,9999
              </span>
              <span className="font-jakarta font-normal text-lg">
                Toplam Maliyet
              </span>
            </div>
          </div>
        </div>

        <div className="flex justify-center md:flex-row flex-col items-center pt-32 p-10 md:p-0">
          <h1 className="lg:w-[332px]  md:w-full font-amatic font-bold text-5xl lg:mr-20 text-black">
            Lorem Ipsum Dolor Sit Consectetur Adipiscing Elit Adipiscing
          </h1>
          <p className="lg:w-[567px] md:w-full font-jakarta font-normal text-base text-[#57544F] pt-10 md:pt-0">
            Morbi accumsan porta eros ac dignissim. Maecenas eleifend, nibh in
            accumsan auctor, est ipsum eleifend erat, eget viverra quam dolor
            sed elit. Donec ut placerat metus. Etiam bibendum nisi maximus
            laoreet lacinia. Etiam orci mi, vulputate ac eleifend sed, semper et
            purus. Ut hendrerit quis risus at ultricies. Nam sed dui sit amet
            nibh malesuada malesuada. Duis facilisis vel nisl a facilisis. Sed
            sagittis volutpat tortor, quis sodales odio malesuada in. Vestibulum
            ante ipsum primis in faucibus orci luctus et ultrices posuere
            cubilia curae; Aliquam cursus nibh sed risus fermentum, a ultrices
            turpis eleifend. In vel vestibulum erat. Integer a purus sit amet
            enim facilisis posuere vel tempor lorem. Sed dignissim enim at mi
            luctus porttitor.
          </p>
        </div>

        {/* PHOTO GALLERY */}

        <div className="flex justify-center md:w-1/1 w-full xs:w-1/">
          <div>
            <h1 className="font-jakarta font-normal text-lg text-black">
              Güler Taşdemir
            </h1>
          </div>
          <div className="flex">
            <Image src="/gallery2.png" width={242} height={242} />
            <Image src="/gallery1.png" width={242} height={242} />
            <Image src="/gallery3.png" width={242} height={242} />
            <Image src="/gallery4.png" width={242} height={242} />
          </div>
        </div>

        {/* HOME STATUS */}

        <div className="flex flex-col mt-8">
          <div className="flex justify-center items-center mb-8">
            <h1
              onClick={changeHomes}
              className={showHomes ? `mr-16 cursor-pointer font-amatic font-bold text-[40px] text-headerColor`:`mr-16 cursor-pointer font-amatic font-bold text-[40px] text-[#57544F]`}
            >
              Tadilat Bekleyen Evler
            </h1>
            <h1
              onClick={changeHomes}
              className={!showHomes ? `mr-16 cursor-pointer font-amatic font-bold text-[40px]  text-headerColor `:`mr-16 cursor-pointer font-amatic font-bold text-[40px] text-[#57544F] `}
            >
              Teslim Edilen Evler
            </h1>
          </div>

          {showHomes ? <Alteration /> : <Delivery />}
            
        </div>
      </div>
    </div>
  );
}
