import Head from "next/head";
import { Icon } from "../icons/Icon";
import Image from "next/image";
import Link from "next/link";
import { useFormik } from "formik";
import * as Yup from "yup";
import { Formik } from "formik";

export default function Support() {
  const formik = useFormik({
    initialValues: {
      firstName: "",
      lastName: "",
      email: "",
      phone:"",
      description:""
    },
    validationSchema: Yup.object({
      firstName: Yup.string()
        .max(15, "15 Karakterden fazla girilemez")
        .required("Lütfen Adınızı Giriniz"),
      lastName: Yup.string()
        .max(15, "15 Karakterden fazla girilemez")
        .required("Lütfen Soyadınızı Giriniz"),
      phone: Yup.string()
        .required("Lütfen numaranızı giriniz"),
        description: Yup.string(),
      email: Yup.string().email("Geçersiz e-posta adresi").required("Lütfen e-mail adresinizi giriniz."),
    }),
    onSubmit: (values) => {
      console.log(JSON.stringify(values, null, 2));
      formik.resetForm();
    },
  });
  return (
    <>
      <Head>
        <title>Ev Tadilat Detay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full bg-[#F9B399] h-[6px]"></div>
      <div className="container mx-auto">
        <div className="flex">
          <div className="w-full md:flex justify-around hidden">
            <div className="pt-[7.438rem]">
              <Icon name="leftCloud" />
            </div>
            <div className="pt-[6.25rem]">
              <h1 className="font-amatic font-bold md:text-[80px] text-5xl text-black text-center">
                DESTEK VER
              </h1>
            </div>
            <div className="pt-[5rem]">
              <Icon name="rightCloud" />
            </div>
          </div>
          <Link href="/">
        <span className="cursor-pointer w-[70px] h-[70px] mt-11">  <Icon name="exit" /></span>
          </Link>
        </div>
        {/* BASLIK */}
        <div className="flex justify-center items-center ">
          <h1 className="w-2/4 text-center font-jakarta font-normal text-base text-[#57544F] pt-8 leading-[34px]">
            Sevgili Hayır Sever, <b>Güler Taşdemir</b> isimli yardıma muhtaç
            kişiye yapmak istediğiniz destek bizi çok mutlu etti. Lütfen yapmak
            istediğiniz desteği bize bildirirseniz, sizinle en kısa sürede
            iletişime geçeceğiz.
          </h1>
        </div>

        {/* ICERIKLER  */}

        <div className="flex flex-col justify-center items-center bg-gray-00 w-full  pt-16">
          <div className="flex flex-col items-center bg-white text-center rounded-[10px]">
            <div
              className="flex md:flex-row flex-col justify-around w-full py-10  items-center
            "
            >
              <div className="flex">
                <div className="flex flex-col">
                  <h1 className="font-jakarta font-semibold text-base text-[#57544F] leading-5">
                    TADİLAT DURUMU
                  </h1>
                  <h1 className="font-jakarta font-normal text-xl text-black leading-8">
                    Balkon Tadilatı
                  </h1>
                </div>
                <div className="flex flex-col">
                  <h1 className="font-jakarta font-semibold text-base text-[#57544F] ml-10 leading-5">
                    TADİLAT MALİYETİ
                  </h1>
                  <h1 className="font-jakarta font-normal text-xl text-black leading-8 ">
                    3.000TL
                  </h1>
                </div>
              </div>
              <div className="flex ">
                <div className="flex flex-col md:pt-0 pt-10 px-5 md:px-0">
                  <h1 className="font-jakarta font-semibold text-base text-left text-[#57544F] ">
                    DESTEK DURUMU
                  </h1>
                  <div className="flex">
                    <div className="flex pr-10">
                      <input type="radio" name="" id="" />
                      <h1 className="font-normal text-base font-jakarta text-black ml-1 leading-6">
                        Maliyeti Karşıla
                      </h1>
                    </div>
                    <div className="flex">
                      <input type="radio" name="" id="" />
                      <h1 className="font-normal text-base font-jakarta text-black ml-1 leading-6">
                        Tadilatı Ben yapacağım
                      </h1>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex w-full h-[1px] bg-[#0000001a]"></div>

            {/* INPUT */}
            <div class="lg:py-10  max-w-screen-md px-5">
              <form onSubmit={formik.handleSubmit} className="space-y-8 ">
                <div className="flex  flex-col">
                  <div className="flex md:flex-row flex-col justify-center items-center pt-3 md:pt-0">
                    <input
                      type="text"
                      id="firstName"
                      name="firstName"
                      class="shadow-sm md:w-96 w-64 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block  p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                      placeholder="Adınız"
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      value={formik.values.firstName}
                    />

                    <input
                      type="text"
                      id="lastName"
                      name="lastName"
                      class="shadow-sm md:w-96 w-64 md:ml-4 mt-3 md:mt-0 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block  p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                      placeholder="Soyadınız"
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      value={formik.values.lastName}
                    />
                  </div>
                  <div className="flex items-center justify-around ">
                    {formik.touched.firstName && formik.errors.firstName ? (
                      <div className="text-red-500">
                        {formik.errors.firstName}
                      </div>
                    ) : null}
                    {formik.touched.lastName && formik.errors.lastName ? (
                      <div className="text-red-500">{formik.errors.lastName}</div>
                    ) : null}
                  </div>
                  <div className="flex md:flex-row flex-col md:pt-8 pt-3 justify-center items-center">
                    <input
                      type="text"
                      id="phone"
                      name="phone"
                      class="shadow-sm md:w-96 w-64 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block  p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                      placeholder="Telefon Numaranız"
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      value={formik.values.phone}
                    />
                    <input
                      type="email"
                      id="email"
                      name="email"
                      class="shadow-sm md:ml-4 mt-3 md:mt-0 md:w-96 w-64 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block  p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                      placeholder="Mail Adresiniz"
                      onChange={formik.handleChange}
                      onBlur={formik.handleBlur}
                      value={formik.values.email}
                    />
             
                  </div>
                  <div className="flex items-center justify-around">
                    {formik.touched.phone && formik.errors.phone ? (
                      <div className="text-red-500">
                        {formik.errors.phone}
                      </div>
                    ) : null}
                    {formik.touched.email && formik.errors.email ? (
                      <div className="text-red-500">{formik.errors.email}</div>
                    ) : null}
                  </div>
                </div>

                <div class="sm:col-span-2 justify-center items-center">
                  <textarea
                    id="message"
                    rows="2"
                    class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                    placeholder="Varsa Mesajınız"
                    onChange={formik.handleChange}
                    onBlur={formik.handleBlur}
                  
                  ></textarea>
                </div>
       
                <div className="w-full flex justify-center items-center">
                  <button
                    type="submit"
                    class="py-3 w-[18.75rem] text-center px-5 bg-[#92CFA3] text-base font-medium  text-black rounded-[5px] "
                  >
                    Gönder
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <Image
        src="/bg.png"
        layout="responsive"
        width={40}
        height={5}
        objectFit="cover"
      />
    </>
  );
}
