import Head from "next/head";
import { Icon } from "../icons/Icon";
import Image from "next/image";
import Link from "next/link";

export default function Support() {
  return (
    <>
      <Head>
        <title>Ev Tadilat Detay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full bg-[#F9B399] h-[6px]"></div>
      <div className="container mx-auto">
        <div className="flex">
          <div className="w-full flex justify-around">
            <div className="pt-[7.438rem]">
              <Icon name="leftCloud" />
            </div>
            <div className="pt-[6.25rem]">
              <h1 className="font-amatic font-bold md:text-[80px] text-5xl text-black text-center">
                DESTEK VER
              </h1>
            </div>
            <div className="pt-[5rem]">
              <Icon name="rightCloud" />
            </div>
          </div>
          <Link href="/">
            <span className="w-[50px] h-[50px] rounded-full flex cursor-pointer justify-center items-center text-[#57544F] text-xl bg-[#57544f33]">
              X
            </span>
          </Link>
        </div>
        {/* BASLIK */}
        <div className="flex justify-center items-center ">
          <h1 className="w-2/4 text-center font-jakarta font-normal text-base text-[#57544F] pt-8">
            Sevgili Hayır Sever, <b>Güler Taşdemir</b> isimli yardıma muhtaç
            kişiye yapmak istediğiniz destek bizi çok mutlu etti. Lütfen yapmak
            istediğiniz desteği bize bildirirseniz, sizinle en kısa sürede
            iletişime geçeceğiz.
          </h1>
        </div>

        {/* ICERIKLER  */}

        <div className="flex flex-col justify-center items-center bg-gray-00 w-full  pt-16">
          <div className="flex flex-col  bg-white text-center rounded-[10px]">
            <div
              className="flex justify-between px-5 py-10
            "
            >
              <div className="flex">
                <div className="flex flex-col">
                  <h1 className="font-jakarta font-semibold text-base text-[#57544F]">TADİLAT DURUMU</h1>
                  <h1 className="font-jakarta font-normal text-xl text-black">Balkon Tadilatı</h1>
                </div>
                <div className="flex flex-col">
                  <h1 className="font-jakarta font-semibold text-base text-[#57544F] ml-10">TADİLAT MALİYETİ</h1>
                  <h1 className="font-jakarta font-normal text-xl text-black">3.000TL</h1>
                </div>
              </div>
              <div className="flex">
                <div className="flex flex-col">
                  <h1 className="font-jakarta font-semibold text-base text-left text-[#57544F]">DESTEK DURUMU</h1>
                  <div className="flex">
                    <div className="flex pr-10">
                      <input type="radio" name="" id="" />
                      <h1 className="font-normal text-base font-jakarta text-black">Maliyeti Karşıla</h1>
                    </div>
                    <div className="flex">
                      <input type="radio" name="" id="" />
                      <h1 className="font-normal text-base font-jakarta text-black">Tadilatı Ben yapacağım </h1>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex w-full h-[1px] bg-[#0000001a]"></div>

            {/* INPUT */}
            <div class="lg:py-10 px-4 max-w-screen-md">
              <form action="#" class="space-y-8">
                <div className="flex  flex-col">
                  <div className="flex md:flex-row flex-col">
                    <input
                      type="text"
                      id="name"
                      name="name"
                      class="shadow-sm  bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-96 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                      placeholder="Adınız"
                      required
                    />
                    <input
                      type="text"
                      id="surname"
                      name="surname"
                      class="shadow-sm ml-4 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-96 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                      placeholder="Soyadınız"
                      required
                    />
                  </div>
                  <div className="flex md:flex-row flex-col md:pt-8 pt-3">
                    <input
                      type="text"
                      id="surname"
                      name="phone"
                      class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-96 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                      placeholder="Telefon Numaranız"
                      required
                    />
                    <input
                      type="email"
                      id="email"
                      name="email"
                      class="shadow-sm ml-4 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-96 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                      placeholder="Mail Adresiniz"
                      required
                    />
                  </div>
                </div>

                <div class="sm:col-span-2">
                  <textarea
                    id="message"
                    rows="2"
                    class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                    placeholder="Varsa Mesajınız"
                  ></textarea>
                </div>
          <div className="w-full flex justify-end items-end">
          <button
                  type="submit"
                  class="py-3 w-[18.75rem] text-center px-5 bg-[#92CFA3] text-base font-medium  text-black rounded-[5px] "
                >
                  Gönder
                </button>
          </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <Image
        src="/bg.png"
        layout="responsive"
        width={40}
        height={5}
        objectFit="cover"
      />
    </>
  );
}
